name: floor_sqlcipher
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the runtime dependency.  Updated to work with sqflite_sqlcipher.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  collection: ^1.15.0
  floor_annotation:
    git:
      url: git@github.com:mmhg-inc/floor_sqlcipher.git
      path: floor_annotation
      ref: develop
  flutter:
    sdk: flutter
  meta: ^1.7.0
  path: ^1.8.3
  sqflite_common_ffi: ^2.1.1+1
  sqflite_sqlcipher: ^2.2.1
  sqlparser: ^0.27.0

dev_dependencies:
  build_runner: ^2.1.2
  floor_generator:
    git:
      url: git@github.com:mmhg-inc/floor_sqlcipher.git
      path: floor_generator
      ref: develop
  flutter_test:
    sdk: flutter
  matcher: ^0.12.10
  mockito: ^5.0.15
